name: MicroPython Integration

on:
  workflow_dispatch:
  push:
    branches: [main]

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.13'
      - run: pip install -e .
      - run: python -m unittest discover tests/ -v

  micropython:
    runs-on: [self-hosted, Linux]
    needs: unit-tests
    strategy:
      fail-fast: false
      matrix:
        device: [ESP32]
    steps:
      - uses: actions/checkout@v4

      - name: Install packages
        run: |
          $HOME/actions-runner/.venv/bin/pip install -e .
          $HOME/actions-runner/.venv/bin/pip install uhttp-client

      - name: MicroPython tests (${{ matrix.device }})
        run: |
          export PATH="$HOME/actions-runner/.venv/bin:$PATH"
          export MPY_TEST_PORT="$(cat $HOME/actions-runner/.config/mpytool/${{ matrix.device }})"
          export MPY_WIFI_SSID="$(jq -r .ssid $HOME/actions-runner/.config/uhttp/wifi.json)"
          export MPY_WIFI_PASSWORD="$(jq -r .password $HOME/actions-runner/.config/uhttp/wifi.json)"
          python -m unittest tests.test_mpy_integration -v
